version: '3'

services:
  mysql:
    container_name: docker_mysql
    build: ./mysql/
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    image: original_mysql_world
    environment:
      MYSQL_DATABASE: development_mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "4306:3306"